#!/usr/bin/env bash
set -euo pipefail

echo "========================================"
echo "  TACH MONOREPO THANH CAC REPO RIENG"
echo "========================================"
echo ""
echo "MoI SERVICE CAN 2 REPO:"
echo "  1. Source repo: Code + Dockerfile + GitHub Actions CI"
echo "  2. Config repo: K8s manifests + ArgoCD CD"
echo ""
echo "Luong lam viec tu dong:"
echo "  Push code -> GitHub Actions build -> Push Docker image"
echo "       -> Tu dong cap nhat config repo -> ArgoCD sync"
echo ""

GITHUB_USER="${GITHUB_USER:-Duong-Vu-practice-workspace}"

echo "=== Danh sach can tach ==="
echo ""
echo "  SERVICE            | SOURCE REPO                          | CONFIG REPO"
echo "  -------------------|--------------------------------------|--------------------------------------"
echo "  config-server      | grading-config-server-test2          | grading-config-server-config-test2"
echo "  gateway            | grading-gateway-test2                | grading-gateway-config-test2"
echo "  assignment-service | grading-assignment-service-test2     | grading-assignment-service-config-test2"
echo "  submission-service | grading-submission-service-test2     | grading-submission-service-config-test2"
echo "  grading-service    | grading-executor-service-test2       | grading-executor-service-config-test2"
echo "  result-service     | grading-result-service-test2         | grading-result-service-config-test2"
echo "  notification-service | grading-notification-service-test2 | grading-notification-service-config-test2"
echo "  common-lib         | grading-common-lib-test2             | (khong can)"
echo ""

echo "=== Huong dan tach ==="
echo ""
echo "Buoc 1: Tao 2 repo tren GitHub cho moi service"
echo "  - Source repo: grading-<service>-test2"
echo "  - Config repo: grading-<service>-config-test2"
echo ""
echo "Buoc 2: Tao GitHub Personal Access Token (PAT)"
echo "  - Vao https://github.com/settings/tokens"
echo "  - Generate new token (classic)"
echo "  - Select scope: repo (full control)"
echo "  - Copy token"
echo ""
echo "Buoc 3: Them token vao Source repo"
echo "  - Vao Source repo > Settings > Secrets and variables > Actions"
echo "  - Them secret: CONFIG_REPO_TOKEN = <token vua tao>"
echo "  - Them secret: DOCKERHUB_USERNAME = <username>"
echo "  - Them secret: DOCKERHUB_TOKEN = <token>"
echo ""
echo "Buoc 4: Copy source code vao Source repo"
echo "  mkdir /tmp/<service> && cd /tmp/<service>"
echo "  cp -r <path-to-repo>/services/<service>/* ."
echo "  cp <path-to-repo>/services/<service>/Dockerfile ."
echo "  # Sua SERVICE_NAME trong .github/workflows/build.yml"
echo "  git init && git add . && git commit -m 'Initial'"
echo "  git remote add origin https://github.com/${GITHUB_USER}/grading-<service>-test2.git"
echo "  git push -u origin main"
echo ""
echo "Buoc 5: Copy config vao Config repo"
echo "  mkdir /tmp/<service>-config && cd /tmp/<service>-config"
echo "  cp <path-to-repo>/config-repos/<service>/* ."
echo "  git init && git add . && git commit -m 'Initial'"
echo "  git remote add origin https://github.com/${GITHUB_USER}/grading-<service>-config-test2.git"
echo "  git push -u origin main"
echo ""
echo "Buoc 6: Apply ArgoCD Application"
echo "  kubectl apply -f <path-to-repo>/deploy/argocd-apps/<service>.yaml"
echo ""
echo "=== Common Library ==="
echo ""
echo "  Tao repo: ${GITHUB_USER}/grading-common-lib-test2"
echo "  Copy services/common-lib/* vao repo"
echo "  Push de GitHub Actions publish len GitHub Packages"
echo ""
