tunnel: dev2-web-grading
credentials-file: /etc/cloudflared/7fdb94b6-9741-4f78-bfdc-a8e6e3d37119.json
ingress:
  - hostname: dev2-api.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-assignment.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-submission.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-grading.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-result.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-notification.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-config.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-argocd.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - hostname: dev2-keycloak.vucongtuanduong.dpdns.org
    service: http://localhost:31242

  - service: http_status:404
