tunnel: 3b0d7940-ebf3-4aed-8d62-68514f0fe3d5
credentials-file: /etc/cloudflared/3b0d7940-ebf3-4aed-8d62-68514f0fe3d5.json
ingress:
  # Gateway
  - hostname: dev1-api.vucongtuanduong.dpdns.org
    service: http://localhost:30000

  # Assignment Service
  - hostname: dev1-assignment.vucongtuanduong.dpdns.org
    service: http://localhost:30001

  # Submission Service
  - hostname: dev1-submission.vucongtuanduong.dpdns.org
    service: http://localhost:30002

  # Grading Service
  - hostname: dev1-grading.vucongtuanduong.dpdns.org
    service: http://localhost:30003

  # Result Service
  - hostname: dev1-result.vucongtuanduong.dpdns.org
    service: http://localhost:30004

  # Notification Service
  - hostname: dev1-notification.vucongtuanduong.dpdns.org
    service: http://localhost:30005

  # ArgoCD
  - hostname: dev1-argocd.vucongtuanduong.dpdns.org
    service: http://localhost:8080

  # Catch-all
  - service: http_status:404