apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: submission-service
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Duong-Vu-practice-workspace/grading-config-test2.git
    targetRevision: main
    path: .
    helm:
      valueFiles:
        - overlays/stg/submission-service-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: web-grading
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
