apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-service
  namespace: grading-platform
  labels:
    app: result-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: result-service
  template:
    metadata:
      labels:
        app: result-service
    spec:
      containers:
        - name: result-service
          image: grading/result-service:latest
          ports:
            - containerPort: 8084
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: result_db
            - name: DB_USERNAME
              value: postgres
            - name: DB_PASSWORD
              value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  namespace: grading-platform
spec:
  selector:
    app: result-service
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
